import linkedlist.SinglyLinkedList;

public class Driver {
    public static void main(String[] args) {

        SinglyLinkedList singlyLinkedList = new SinglyLinkedList();
        singlyLinkedList.push(5);  // Success
        singlyLinkedList.push(10);  // Success
        singlyLinkedList.push(15);  // Success
        singlyLinkedList.push(20);  // Success
        singlyLinkedList.push(25);  // Success

        // Code Generated by Sidekick is for learning and experimentation purposes only.
        System.out.println(singlyLinkedList.remove(2).value);  // 15
        System.out.println(singlyLinkedList.remove(100));  // null
        System.out.println(singlyLinkedList.size);  // 4
        System.out.println(singlyLinkedList.head.value);  // 5
        System.out.println(singlyLinkedList.head.next.value);  // 10
        System.out.println(singlyLinkedList.head.next.next.value);  // 20


    }
}
